<?php

namespace nadzif\base\components\console;

class Migration extends \yii\db\Migration
{
    /**
     * @var string
     */
    protected $tableOptions;

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();


        echo 'bupind =' . $this->getDb()->driverName;
        // switch based on driver name
        switch ($this->getDb()->driverName) {

            case 'mysql':
                $this->tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
                break;
            default:
                $this->tableOptions = null;
        }
    }

    public function setForeignKey($table, $columns, $refTable, $refColumns, $delete = 'CASCADE', $update = 'CASCADE')
    {
        $name = $this->formatForeignKeyName($table, $refTable);
        parent::addForeignKey($name, $table, $columns, $refTable, $refColumns, $delete, $update);
    }

    public function formatForeignKeyName($tableNameForeign, $tableNamePrimary)
    {

        $tableNameForeign = explode('.', $tableNameForeign);
        $tableNameForeign = $tableNameForeign[count($tableNameForeign) - 1];
        $tableNameForeign = trim($tableNameForeign, '{}');
        $tableNameForeign = str_replace('%', '', $tableNameForeign);

        $tableNamePrimary = explode('.', $tableNamePrimary);
        $tableNamePrimary = $tableNamePrimary[count($tableNamePrimary) - 1];
        $tableNamePrimary = trim($tableNamePrimary, '{}');
        $tableNamePrimary = str_replace('%', '', $tableNamePrimary);

        return 'fk_' . $tableNameForeign . '_' . $tableNamePrimary;
    }


    public function addUuidPrimaryKey($table, $columns)
    {
        $originalTableName = explode('.', $table);
        $originalTableName = $originalTableName[count($originalTableName) - 1];
        $originalTableName = trim($originalTableName, '{}');
        $originalTableName = str_replace('%', '', $originalTableName);

        $suggestedKeyName = ucwords($originalTableName);

        foreach ($columns as $column) {
            $this->addColumn($table, $column, $this->string(36)->notNull());
            $suggestedKeyName .= ucwords($column);
        }

        parent::addPrimaryKey($suggestedKeyName, $table, $columns);
    }

    public function addLogColumns($table)
    {
        $this->addColumn($table, 'createdAt', $this->dateTime());
        $this->addColumn($table, 'createdBy', $this->string());
        $this->addColumn($table, 'updatedAt', $this->dateTime());
        $this->addColumn($table, 'updatedBy', $this->string());

        $originalTableName = explode('.', $table);
        $originalTableName = $originalTableName[count($originalTableName) - 1];
        $originalTableName = trim($originalTableName, '{}');
        $originalTableName = str_replace('%', '', $originalTableName);

        $this->createIndex("Index" . ucwords($originalTableName) . 'CreatedAt', $table, "createdAt");
    }

    public function createTable($table, $columns, $options = null)
    {
        parent::createTable($table, $columns, $this->tableOptions); // TODO: Change the autogenerated stub
    }
}
